version: '3.8'

services:
  playwright-mcp:
    build: 
      context: .
      args:
        PORT: ${PORT:-8931}
    ports:
      - "${PORT:-8931}:${PORT:-8931}"
    environment:
      - PORT=${PORT:-8931}
    restart: unless-stopped
    # Optional: Add health check
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:${PORT:-8931}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s