version: '3.8'

services:
  playwright-mcp:
    build: .
    container_name: playwright-mcp-server
    ports:
      - "${MCP_HOST_PORT:-8931}:8931"
    environment:
      - DEBUG=${DEBUG:-}
      - MCP_OUTPUT_DIR=/app/output
    volumes:
      - ./output:/app/output
      - ./config:/app/config:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8931/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - playwright-network

networks:
  playwright-network:
    driver: bridge