[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
healthcheckPath = "/health"
healthcheckTimeout = 300

[environments.production]
variables = {
  NODE_ENV = "production",
  PLAYWRIGHT_BROWSERS_PATH = "/ms-playwright",
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD = "1",
  MCP_WEBSOCKET_TIMEOUT = "10000",
  MCP_CONNECTION_TIMEOUT = "15000"
} 